# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI3.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(425, 386)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.FileName = QtWidgets.QLineEdit(self.centralwidget)
        self.FileName.setGeometry(QtCore.QRect(190, 20, 181, 22))
        self.FileName.setObjectName("FileName")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 20, 181, 16))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 70, 361, 28))
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 130, 151, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 170, 151, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 210, 131, 16))
        self.label_4.setObjectName("label_4")
        self.MaxL = QtWidgets.QLineEdit(self.centralwidget)
        self.MaxL.setGeometry(QtCore.QRect(190, 130, 141, 22))
        self.MaxL.setObjectName("MaxL")
        self.MinL = QtWidgets.QLineEdit(self.centralwidget)
        self.MinL.setGeometry(QtCore.QRect(190, 170, 141, 22))
        self.MinL.setObjectName("MinL")
        self.SrL = QtWidgets.QLineEdit(self.centralwidget)
        self.SrL.setGeometry(QtCore.QRect(190, 210, 141, 22))
        self.SrL.setObjectName("SrL")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 425, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Числа из файла"))
        self.label.setText(_translate("MainWindow", "Введите название файла: "))
        self.pushButton.setText(_translate("MainWindow", "Выполнить"))
        self.label_2.setText(_translate("MainWindow", "Максимальное значение:"))
        self.label_3.setText(_translate("MainWindow", "Минимальное значение:"))
        self.label_4.setText(_translate("MainWindow", "Среденее значение:"))
