# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI4.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(616, 592)
        MainWindow.setMinimumSize(QtCore.QSize(615, 592))
        MainWindow.setMaximumSize(QtCore.QSize(616, 592))
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(10, 50, 591, 471))
        self.textBrowser.setObjectName("textBrowser")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 381, 30))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.OpenF = QtWidgets.QPushButton(self.layoutWidget)
        self.OpenF.setObjectName("OpenF")
        self.horizontalLayout.addWidget(self.OpenF)
        self.SaveF = QtWidgets.QPushButton(self.layoutWidget)
        self.SaveF.setObjectName("SaveF")
        self.horizontalLayout.addWidget(self.SaveF)
        self.CreateF = QtWidgets.QPushButton(self.layoutWidget)
        self.CreateF.setObjectName("CreateF")
        self.horizontalLayout.addWidget(self.CreateF)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 616, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RText"))
        self.OpenF.setText(_translate("MainWindow", "Открыть"))
        self.SaveF.setText(_translate("MainWindow", "Сохранить"))
        self.CreateF.setText(_translate("MainWindow", "Создать"))
